version: '3'
networks:
  proxy:
    external:
      name: nginx_proxysso
  dbnet:
    internal: true

services:
  back:
    build:
      context: ./back/
      dockerfile: Dockerfile.back
    container_name: back-calendar
    tty: true
    restart: always
    depends_on:
      rethink:
        condition: "service_started"
    networks:
      - proxy
      - dbnet
    expose:
      - 8080
    healthcheck:
      test: exit $$( curl -so /dev/null --fail http://127.0.0.1:8080 && echo 0 || echo 1 )
      interval: 30s
      timeout: 1s
      retries: 1
    volumes:
      - ./back/src:/home/api:ro
      - ./source:/source:ro
    environment:
      API_HOST: 0.0.0.0
      API_PORT: 8080
      API_WEBA: '*'
      API_MOD: PROD
      SSO_TOKEN: 5e3480c25a364b1ca85ae6a95ddb716c
      SSO_REGISTRY: 61f64eea-a2f7-49de-87ef-d5e7afc7370f
      VIRTUAL_HOST: calendar.project.eliotctl.fr
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: calendar.project.eliotctl.fr
      LETSENCRYPT_EMAIL: eliot.courtel@wanadoo.fr


  rethink:
    image: rethinkdb:latest
    container_name: rethink-calendar
    restart: always
    expose:
      - 28015
    volumes:
      - ./db/rethink/data:/data:rw
    command: rethinkdb --bind all -d /data
    networks:
      - dbnet
